// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';
import {main} from '../models';

export function Greet(arg1:string):Promise<string>;

export function Kick():void;

export function Load(arg1:context.Context):Promise<main.Config|Error>;

export function Save(arg1:context.Context):Promise<Error>;
