// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function Kick() {
  return window['go']['main']['App']['Kick']();
}

export function Load(arg1) {
  return window['go']['main']['App']['Load'](arg1);
}

export function Save(arg1) {
  return window['go']['main']['App']['Save'](arg1);
}
